export async function up(sql) {
  await sql`
    CREATE TABLE animals (
      id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name varchar(40) NOT NULL,
      type varchar(40) NOT NULL,
      accessory varchar(40) NOT NULL
    )
  `;
}

export async function down(sql) {
  await sql`
    DROP TABLE animals
  `;
}
